### ISSUE TITLE
Try folder_locker.bat and snake.bat

### ISSUE THREAD

**Issue by double-beep** [Help-batch/batch#14]
Hi @helper-beep @anyone_who_likes_*.bat,
Please try folder_locker.bat and pay attention to my reviews.
Thank you.

**Comment by double-beep** [comment]
Reopen for comments.!

**Comment by helper-beep** [comment]
Try and merge also snake.bat

**Comment by double-beep** [comment]
Congrats, I tried!! Amazing!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by double-beep** [comment]
See #31
